name: Python Package using Conda

on: 
 push:
  branches:
    - main

jobs:
  build:
   runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
    - name: Add libs
      run: |
        # libaries for my code
    - name: Install dependencies
      run: |
        pip install asyncio datetime playwright
      run: |
        python main.py
